import { prisma } from '@/infrastructure/db/prisma'
import { getCodingProvider, type CodingEngineId, AiProviderError } from '@/infrastructure/ai'
import { asInstallation, GithubApiError } from '@/infrastructure/github/client'
import { recordActivity } from '@/features/activity/service'
import { branchNameFor, TICKET_KIND_LABELS } from '@/core/domain/git-refs'
import { uniqueBranch } from '@/core/domain/ai-fix'
import { runFixAgent } from './agent'
import { RepoWorkspace } from './workspace'

/**
 * Runs one "Fix with AI" attempt to completion.
 *
 * Called after the request that started it has already answered, so every
 * outcome — a pull request, no changes, or a failure with a reason — is written
 * to the run row, never thrown at a caller who is no longer listening.
 */
export async function executeFixRun(runId: string): Promise<void> {
  const run = await prisma.aiFixRun.findUnique({
    where: { id: runId },
    select: {
      id: true,
      provider: true,
      model: true,
      instructions: true,
      requestedById: true,
      requestedBy: { select: { name: true } },
      ticket: {
        select: {
          id: true,
          key: true,
          title: true,
          description: true,
          projectId: true,
          type: { select: { kind: true } },
        },
      },
      repo: {
        select: {
          fullName: true,
          defaultBranch: true,
          installation: { select: { installationId: true } },
        },
      },
    },
  })
  if (!run) return

  await prisma.aiFixRun.update({ where: { id: runId }, data: { status: 'RUNNING', startedAt: new Date() } })

  const { ticket, repo } = run
  const installationId = repo.installation.installationId

  try {
    const provider = getCodingProvider(run.provider as CodingEngineId)
    const workspace = await RepoWorkspace.open(installationId, repo.fullName, repo.defaultBranch)

    const result = await runFixAgent({
      provider,
      workspace,
      ticket: {
        key: ticket.key,
        title: ticket.title,
        description: ticket.description,
        kindLabel: TICKET_KIND_LABELS[ticket.type.kind].label,
      },
      instructions: run.instructions,
      // Written every turn, so a run that fails midway still shows what it
      // did and what it cost.
      onProgress: async ({ turns, transcript, inputTokens, outputTokens }) => {
        await prisma.aiFixRun.update({
          where: { id: runId },
          data: { turns, transcript: transcript.join('\n'), inputTokens, outputTokens },
        })
      },
    })

    const usage = {
      turns: result.turns,
      inputTokens: result.inputTokens,
      outputTokens: result.outputTokens,
      transcript: result.transcript.join('\n'),
    }

    const changes = await workspace.changes()
    if (changes.length === 0) {
      await prisma.aiFixRun.update({
        where: { id: runId },
        data: { ...usage, status: 'NO_CHANGES', summary: result.summary, finishedAt: new Date() },
      })
      return
    }

    // The ticket's own branch name, so the existing integration links it —
    // suffixed if a person (or an earlier run) already has that branch.
    const base = branchNameFor(ticket.key, ticket.title, ticket.type.kind)
    const existing = await asInstallation<Array<{ ref: string }>>(
      installationId,
      `/repos/${repo.fullName}/git/matching-refs/heads/${base}`,
    )
    const branch = uniqueBranch(base, new Set(existing.map((ref) => ref.ref.replace('refs/heads/', ''))))

    const footer = `Generated by TaskForge's AI fix (${run.provider} · ${run.model}) for ${ticket.key}${
      run.requestedBy ? `, requested by ${run.requestedBy.name}` : ''
    }.`
    const commit = await workspace.commit(
      branch,
      `${ticket.key}: ${result.title}\n\n${result.summary}\n\n${footer}`,
    )

    const pull = await asInstallation<{ number: number; html_url: string }>(
      installationId,
      `/repos/${repo.fullName}/pulls`,
      {
        method: 'POST',
        body: {
          title: `${ticket.key}: ${result.title}`,
          head: branch,
          base: repo.defaultBranch,
          body: [
            result.summary,
            '',
            '---',
            `${footer} It was written without running the code or its tests — review it as you would any contributor's, and let CI have its say. TaskForge never merges an AI change.`,
            ...(result.finished ? [] : ['', '> The model did not call `finish`, so this may be incomplete.']),
          ].join('\n'),
        },
      },
    )

    await prisma.$transaction(async (tx) => {
      await tx.aiFixRun.update({
        where: { id: runId },
        data: {
          ...usage,
          status: 'SUCCEEDED',
          branch,
          prNumber: pull.number,
          prUrl: pull.html_url,
          summary: result.summary,
          changedFiles: commit.files.join('\n'),
          finishedAt: new Date(),
        },
      })
      await recordActivity(tx, {
        action: 'AI_GENERATED',
        entityType: 'TICKET',
        entityId: ticket.id,
        entityLabel: ticket.key,
        projectId: ticket.projectId,
        ticketId: ticket.id,
        actorId: run.requestedById,
        summary: `had AI open pull request #${pull.number} in ${repo.fullName} (${run.provider} · ${run.model}, ${commit.files.length} ${commit.files.length === 1 ? 'file' : 'files'})`,
      })
    })
  } catch (error) {
    console.error(`[ai-fix] run ${runId} failed:`, error)
    await prisma.aiFixRun.update({
      where: { id: runId },
      data: { status: 'FAILED', error: explain(error), finishedAt: new Date() },
    })
  }
}

/** A failure a person can act on, rather than a stack trace. */
function explain(error: unknown): string {
  if (error instanceof AiProviderError) return error.message
  if (error instanceof GithubApiError) {
    if (error.status === 403 || error.status === 404) {
      return 'GitHub refused the write. The TaskForge app needs read & write access to Contents and Pull requests on this repository — update its permissions on GitHub and accept them on the installation.'
    }
    return `GitHub returned ${error.status}: ${error.message}`
  }
  return error instanceof Error ? error.message.slice(0, 300) : 'The run failed.'
}

/**
 * Runs left QUEUED or RUNNING by a process that died — a redeploy, a function
 * timeout — would otherwise block the ticket forever. Anything that has not
 * moved in fifteen minutes is marked failed.
 */
export async function expireStaleRuns(ticketId?: string) {
  await prisma.aiFixRun.updateMany({
    where: {
      ...(ticketId ? { ticketId } : {}),
      status: { in: ['QUEUED', 'RUNNING'] },
      updatedAt: { lt: new Date(Date.now() - 15 * 60_000) },
    },
    data: {
      status: 'FAILED',
      error: 'The run stopped without reporting back — the server may have restarted or timed out.',
      finishedAt: new Date(),
    },
  })
}
